### ISSUE TITLE
IE8 support broken

### ISSUE THREAD

**Issue by klemens-u** [joeyvandijk/rimg#12]
I just checked a site using rimg.js with IE8 and sadly no images were loaded at all. 
Reproduceable at http://joeyvandijk.github.io/rimg/ 
Error Message: 'console' not defined Line 1 Char 26

**Comment by klemens-u** [comment]
Proposed fix: https://github.com/joeyvandijk/rimg/pull/14

**Comment by joeyvandijk** [comment]
Implemented #14
